Componente Avatar
codigo-de-queijo/cheestorybook pull request #9
Opened 2022-07-04 03:07 UTC by raulhenrique-x3

Esta foi a primeira tentativa de criação do componente Avatar, estou tendo dificuldades em imprimir o componente na tela e estou fazendo essa pull request para que possamos tentar solucionar o problema e concluirmos a criação desse Avatar.

2022-07-04 03:48 UTC, raulhenrique-x3 commented
Problema do componente Avatar corrigido. Após verificar a forma em que o template string se comportava no componente TSX e comparar com exemplos dentro do próprio projeto, pude notar que estava passando incorretamente os códigos no CSS e causando conflito com as expressões imbutidas no template string do TSX.

2022-07-04 04:07 UTC, raulhenrique-x3 commented
Fiz uma correção trocando div para img e também fiz com que fosse possível receber imagens hospedadas para o avatar. Nessa circustância tentarei fazer o processo passar iniciais caso nada seja passado.

2022-07-04 06:13 UTC, raulhenrique-x3 commented
Retirada do template string do src pois, se o componente recebe img que é tipada como string no TS não há a necessidade de usar um template string no src do elemento.

2022-07-05 00:51 UTC, frenetic requested changes

2022-07-05 00:51 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +import { any } from "prop-types";
`any` é padrão do typescript. Então não precisa importar.

2022-07-05 00:51 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    format = "square",
:+1:

2022-07-05 00:51 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    ...props }) => {
remover o `...props`.
Principio da responsabilidade única: https://medium.com/@angelomribeiro/princ%C3%ADpio-da-responsabilidade-%C3%BAnica-6d633087fa4e

Basicamente: seu componente é responsável por fazer uma coisa e apenas essa coisa.
Olhar para outras informações ou responsabilidades que não sejam as desenhadas para esse componente quebra esse princípio.
Faz parte do dever do programador saber que passar dados a mais para essa "função" quebra o funcionamento normal dela.

2022-07-05 00:58 UTC, frenetic requested changes

2022-07-05 00:58 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    const formats = format ? 'component-avatar--square' : 'component-avatar--round'
```suggestion
    const formats = format == "square" ? 'component-avatar--square' : 'component-avatar--round'
```

2022-07-05 00:58 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +                className={['component-avatar', `component-avatar--${size}`, `component-avatar--${format}`, formats].join(' ')}
```suggestion
                className={`component-avatar component-avatar--${size} component-avatar--${format}`}
```

2022-07-05 01:07 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +                {...props}
não precisa desse `{...props}`

2022-07-05 01:07 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    const formats = format ? 'component-avatar--square' : 'component-avatar--round'
```suggestion
    const formats = format ? 'component-avatar--square' : 'component-avatar--round';
```

2022-07-05 01:11 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    const formats = format ? 'component-avatar--square' : 'component-avatar--round'
`formats` é desnecessário, visto que, no componente, vc faz uma concatenação de strings com `format`, que já resolve o seu problema.

2022-07-05 01:12 UTC, frenetic commented on src/components/Avatar/Avatar.stories.tsx
> +import React from "react";
Import desnecessário

2022-07-14 13:11 UTC, raulhenrique-x3 commented
Resolvido problema de imagem quebrada no alt do componente avatar, código enviado para review.

2022-07-18 03:30 UTC, frenetic requested changes

2022-07-18 03:30 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    return `${firstName[0]}${lastName[0]}`
```suggestion
    return `${firstName[0]}${lastName[0]}`;
```

2022-07-18 03:30 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    const [hasNoImg, setHasNoImg] = useState(false)
```suggestion
    const [hasNoImg, setHasNoImg] = useState(false);
```

2022-07-18 03:30 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    const onerror = useCallback(() => setHasNoImg(true), [])
```suggestion
    const onerror = useCallback(() => setHasNoImg(true), []);
```

2022-07-18 03:30 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    const noImg = !src || hasNoImg
```suggestion
    const noImg = !src || hasNoImg;
```

2022-07-18 03:30 UTC, frenetic commented on src/components/Avatar/Avatar.tsx
> +    )
```suggestion
    );
```

2022-07-18 03:34 UTC, frenetic requested changes
Cara, tá quase lá.
Tá ficando muito legal.
Porém, encontrei um bug: Quando você coloca uma imagem e uma string, está aparecendo os 2.

![image](https://user-images.githubusercontent.com/122976/179441549-6ee0d6de-40c8-4dd0-b974-b2ea6a00e2bd.png)

2022-07-26 02:01 UTC, frenetic approved these changes
Parece Dolly Guaraná.

APROVADUUUUUUUUUUUU

2022-07-26 02:01 UTC, merged